### ISSUE TITLE
[Instalation Error] There are types at '...' but this result could not be resolved when respecting package.json "exports".

### ISSUE THREAD

**Issue by Sphirye** [evo-mark/vue3-snackbar#15]
Following the [installation docs](https://evomark.co.uk/open-source-software/vue3-snackbar/) results in the following typescript error (vscode):
```
Could not find a declaration file for module 'vue3-snackbar'. '*path*/node_modules/vue3-snackbar/dist/vue3-snackbar.js' implicitly has an 'any' type.
There are types at '*path*/node_modules/vue3-snackbar/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue3-snackbar' library may need to update its package.json or typings.ts(7016)
```

And the console throws the following error:
```
Error: The following dependencies are imported but could not be resolved:

  node_modules/vue3-snackbar/types (imported by *path*/src/plugins/index.ts)

Are they installed?
    at file://*path*/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:50560:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file://*path*/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:50065:26
```

Using  `require imports` doesnt seem to make a difference, 

Vue Version: 3.4.31
Node Version: v22.0.0
OS: Linux - Fedora 41

**Comment by craigrileyuk** [comment]
Latest release has added types to each of the package.json exports, which should solve this. If you could confirm?

**Comment by Sphirye** [comment]
![image](https://github.com/user-attachments/assets/dd2e2125-6156-4490-bf2e-e5443b4562ca)
Working now, thanks son
